[package]
name = "pallet-vote"
version = "0.1.0"
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cid = "0.6.0"
sp-runtime = { version = "4.0.0-dev", default-features = false, path = "../../../../primitives/runtime" }
pallet-identity = {version = "4.0.0-dev", default-features = false, path = "../../../../frame/identity"}
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = [
	"derive",
] }
frame-support = { default-features = false, version = "4.0.0-dev", path = "../../../../frame/support" }
frame-system = { default-features = false, version = "4.0.0-dev", path = "../../../../frame/system" }
frame-benchmarking = { default-features = false, version = "4.0.0-dev", path = "../../../../frame/benchmarking", optional = true }
sp-core = { default-features = false, version = "4.0.0-dev", path = "../../../../primitives/core" }
sp-io = { default-features = false, version = "4.0.0-dev", path = "../../../../primitives/io" }
sp-std = { default-features = false, version = "4.0.0-dev", path = "../../../../primitives/std" }

[dev-dependencies]
sp-core = { default-features = false, version = "4.0.0-dev", path = "../../../../primitives/core" }
sp-io = { default-features = false, version = "4.0.0-dev", path = "../../../../primitives/io" }
sp-runtime = { default-features = false, version = "4.0.0-dev", path = "../../../../primitives/runtime" }

[features]
default = ['std']
std = [
	'codec/std',
	'frame-support/std',
	'frame-system/std',
	'frame-benchmarking/std',
	'sp-core/std',
	'sp-runtime/std',
	'sp-io/std',
]

runtime-benchmarks = ["frame-benchmarking"]
try-runtime = ["frame-support/try-runtime"]